import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

// Using Ethereal (for testing) or real SMTP if provided
const transporter = nodemailer.createTransport({
  host: process.env.MAIL_HOST || 'smtp.ethereal.email',
  port: parseInt(process.env.MAIL_PORT || '587'),
  auth: {
    user: process.env.MAIL_USER || 'sample@ethereal.email',
    pass: process.env.MAIL_PASS || 'samplepassword',
  },
});

export const sendQueryDetails = async (to: string, queryInfo: any, customMessage?: string, attachments?: any[]) => {
  const mailOptions: any = {
    from: `"Smart Search Assistant" <${process.env.MAIL_FROM}>`,
    to,
    subject: `Expert Analysis: ${queryInfo.query}`,
    attachments: attachments?.map(file => ({
      filename: file.originalname,
      content: file.buffer,
      contentType: file.mimetype
    })),
    html: `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px; border: 1px solid #e2e8f0; border-radius: 24px; background-color: #ffffff; color: #1e293b;">
        <div style="text-align: center; margin-bottom: 30px;">
          <div style="display: inline-block; padding: 12px; background: #f0f9ff; border-radius: 16px;">
            <img src="https://cdn-icons-png.flaticon.com/512/2875/2875433.png" width="40" height="40" alt="icon" />
          </div>
          <h1 style="margin-top: 15px; color: #0f172a; font-size: 24px; font-weight: 800;">Intelligence Report</h1>
        </div>

        <div style="background: #f8fafc; border: 1px solid #f1f5f9; padding: 25px; border-radius: 20px; margin-bottom: 30px;">
          <p style="margin: 0; color: #64748b; font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em;">SEARCH CONTEXT</p>
          <p style="margin: 8px 0 0; color: #0f172a; font-size: 18px; font-weight: 600; font-style: italic;">"${queryInfo.query}"</p>
          <div style="margin-top: 15px; display: flex; gap: 10px;">
            <span style="background: #e0f2fe; color: #0369a1; padding: 4px 12px; border-radius: 100px; font-size: 12px; font-weight: 600;">${queryInfo.category || 'General'}</span>
            <span style="background: #f1f5f9; color: #475569; padding: 4px 12px; border-radius: 100px; font-size: 12px; font-weight: 600;">${queryInfo.engine}</span>
          </div>
        </div>
        
        ${customMessage ? `
        <div style="margin-bottom: 30px;">
          <p style="margin: 0 0 10px; color: #64748b; font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em;">ADMINISTRATOR INSIGHTS</p>
          <div style="background: #fffbeb; border-left: 4px solid #f59e0b; padding: 20px; border-radius: 0 16px 16px 0; color: #92400e; line-height: 1.6; font-size: 15px;">
            ${customMessage.replace(/\n/g, '<br/>')}
          </div>
        </div>
        ` : ''}

        ${attachments && attachments.length > 0 ? `
        <div style="padding-top: 20px; border-top: 1px solid #f1f5f9;">
          <p style="margin: 0 0 10px; color: #64748b; font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em;">ATTACHED RESOURCES</p>
          <p style="color: #475569; font-size: 14px;">${attachments.length} file(s) have been attached for your reference.</p>
        </div>
        ` : ''}

        <div style="margin-top: 40px; text-align: center; border-top: 1px solid #f1f5f9; padding-top: 30px;">
          <p style="color: #94a3b8; font-size: 12px;">
            This analysis was generated by the <strong>Smart Search Assistant</strong>.
          </p>
        </div>
      </div>
    `,
  };

  return transporter.sendMail(mailOptions);
};
